spring:
  application:
    name: member_mariadb_test_20251024

  datasource:
    url: jdbc:mariadb://localhost:3307/testdb
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8888

